create table if not exists public.daily_goal_targets (
  id bigint generated by default as identity primary key,
  date date not null,
  machine_name text not null,
  equipment_label text not null default '',
  imei text,
  obra_code text not null default '',
  source_image_id text not null default '',
  source_file_name text not null default '',
  meta_estacas_total integer not null default 0,
  meta_meq_total numeric(12,2) not null default 0,
  meta_meq_informado numeric(12,2),
  segments jsonb not null default '[]'::jsonb,
  warnings jsonb not null default '[]'::jsonb,
  errors jsonb not null default '[]'::jsonb,
  status text not null default 'confirmed',
  confirmed_by text not null default 'admin',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists daily_goal_targets_date_idx on public.daily_goal_targets (date desc);
create index if not exists daily_goal_targets_machine_idx on public.daily_goal_targets (machine_name);
create index if not exists daily_goal_targets_status_idx on public.daily_goal_targets (status);

create unique index if not exists daily_goal_targets_unique_day_machine_work
on public.daily_goal_targets (date, machine_name, obra_code);
