create table if not exists public.machine_mappings (
  id bigint generated by default as identity primary key,
  imei text not null,
  machine_name text not null,
  obra_code text default '',
  obra_name text not null default 'Obra nao definida',
  daily_goal_estacas integer not null default 0,
  weekly_goal_estacas integer not null default 0,
  active boolean not null default true,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists machine_mappings_imei_idx on public.machine_mappings (imei);
create index if not exists machine_mappings_active_idx on public.machine_mappings (active);

create unique index if not exists machine_mappings_single_active_per_imei
on public.machine_mappings (imei)
where active = true;
