CREATE TABLE IF NOT EXISTS diary_helper_evaluations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  diary_id BIGINT UNSIGNED NOT NULL,
  diary_date DATE NULL DEFAULT NULL,
  operator_user_id BIGINT UNSIGNED NULL DEFAULT NULL,
  helper_user_id BIGINT UNSIGNED NULL DEFAULT NULL,
  helper_name VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  construction_id BIGINT UNSIGNED NULL DEFAULT NULL,
  score TINYINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_diary_helper_evaluations_diary_id (diary_id),
  KEY idx_diary_helper_evaluations_diary_date (diary_date),
  KEY idx_diary_helper_evaluations_helper_user_id (helper_user_id),
  KEY idx_diary_helper_evaluations_operator_user_id (operator_user_id),
  KEY idx_diary_helper_evaluations_construction_id (construction_id),
  KEY idx_diary_helper_evaluations_helper_name (helper_name),
  CONSTRAINT fk_diary_helper_evaluations_diary FOREIGN KEY (diary_id) REFERENCES diaries (id) ON DELETE CASCADE,
  CONSTRAINT fk_diary_helper_evaluations_operator FOREIGN KEY (operator_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_diary_helper_evaluations_helper FOREIGN KEY (helper_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_diary_helper_evaluations_construction FOREIGN KEY (construction_id) REFERENCES constructions (id) ON DELETE SET NULL,
  CONSTRAINT chk_diary_helper_evaluations_score CHECK (score BETWEEN 1 AND 10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
