-- Add cargo column to legacy users table
ALTER TABLE users ADD COLUMN cargo VARCHAR(100) NULL;

-- Update cargo by user ID (matched from employee CSV)
UPDATE users SET cargo = 'Soldas'            WHERE id = 278;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 483;
UPDATE users SET cargo = 'Operador'          WHERE id = 493;
UPDATE users SET cargo = 'Logística - Mot'   WHERE id = 280;
UPDATE users SET cargo = 'Mecânica'          WHERE id = 281;
UPDATE users SET cargo = 'Logística - Mot'   WHERE id = 282;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 283;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 284;
UPDATE users SET cargo = 'Fazenda'           WHERE id = 285;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 655;
UPDATE users SET cargo = 'INSS'              WHERE id = 402;
UPDATE users SET cargo = 'Operador'          WHERE id = 286;
UPDATE users SET cargo = 'Caldeiraria'       WHERE id = 482;
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 287;
UPDATE users SET cargo = 'Logística - Adm'   WHERE id = 638;
UPDATE users SET cargo = 'Gestão'            WHERE id = 451;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 289;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 393;
UPDATE users SET cargo = 'Operador'          WHERE id = 291;
UPDATE users SET cargo = 'RH'                WHERE id = 292;
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 640;
UPDATE users SET cargo = 'Operador'          WHERE id = 293;
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 639;
UPDATE users SET cargo = 'Gestão'            WHERE id = 606;  -- Bruna Garcia (CSV: Bruna Rodrigues Garcia)
UPDATE users SET cargo = 'Mecânica'          WHERE id = 585;
UPDATE users SET cargo = 'Operador'          WHERE id = 296;
UPDATE users SET cargo = 'Operador'          WHERE id = 591;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 297;
UPDATE users SET cargo = 'Operador'          WHERE id = 298;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 650;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 532;
UPDATE users SET cargo = 'Logística - Mot'   WHERE id = 405;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 567;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 673;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 526;
UPDATE users SET cargo = 'Comercial'         WHERE id = 562;
UPDATE users SET cargo = 'Operador'          WHERE id = 300;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 590;
UPDATE users SET cargo = 'Soldas'            WHERE id = 301;
UPDATE users SET cargo = 'Operador'          WHERE id = 302;
UPDATE users SET cargo = 'Comercial'         WHERE id = 304;
UPDATE users SET cargo = 'Operador'          WHERE id = 305;  -- Douglas Charles (CSV: Douglas Charles Pinto)
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 307;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 408;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 517;
UPDATE users SET cargo = 'Caldeiraria'       WHERE id = 309;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 453;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 584;
UPDATE users SET cargo = 'Mecânica'          WHERE id = 311;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 595;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 481;
UPDATE users SET cargo = 'Caldeiraria'       WHERE id = 510;
UPDATE users SET cargo = 'Mecânica'          WHERE id = 414;
UPDATE users SET cargo = 'Financeiro'        WHERE id = 313;
UPDATE users SET cargo = 'Operador'          WHERE id = 573;
UPDATE users SET cargo = 'Gestão'            WHERE id = 401;
UPDATE users SET cargo = 'TST'               WHERE id = 521;
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 316;
UPDATE users SET cargo = 'Caldeiraria'       WHERE id = 317;
UPDATE users SET cargo = 'Mecânica'          WHERE id = 417;
UPDATE users SET cargo = 'Diretor'           WHERE id = 320;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 672;
UPDATE users SET cargo = 'Financeiro'        WHERE id = 597;
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 467;
UPDATE users SET cargo = 'Manutenção'        WHERE id = 649;
UPDATE users SET cargo = 'Operador'          WHERE id = 323;
UPDATE users SET cargo = 'Operador'          WHERE id = 324;
UPDATE users SET cargo = 'Caldeiraria'       WHERE id = 422;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 564;
UPDATE users SET cargo = 'Caldeiraria'       WHERE id = 572;  -- Joao Gabriel Alves dos Santos (CSV typo: Sanntos)
UPDATE users SET cargo = 'Mecânica'          WHERE id = 546;
UPDATE users SET cargo = 'Operador'          WHERE id = 328;
UPDATE users SET cargo = 'Logística - Adm'   WHERE id = 596;
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 329;
UPDATE users SET cargo = 'Soldas'            WHERE id = 674;
UPDATE users SET cargo = 'Caldeiraria'       WHERE id = 529;
UPDATE users SET cargo = 'Operador'          WHERE id = 331;
UPDATE users SET cargo = 'Comercial'         WHERE id = 332;
UPDATE users SET cargo = 'Operador'          WHERE id = 333;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 335;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 336;
UPDATE users SET cargo = 'Caldeiraria'       WHERE id = 337;
UPDATE users SET cargo = 'Mecânica'          WHERE id = 504;
UPDATE users SET cargo = 'Operador'          WHERE id = 339;
UPDATE users SET cargo = 'Logística - OPE'   WHERE id = 561;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 204;
UPDATE users SET cargo = 'Gestão'            WHERE id = 603;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 340;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 588;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 341;
UPDATE users SET cargo = 'Gestão'            WHERE id = 644;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 583;
UPDATE users SET cargo = 'Gestão'            WHERE id = 398;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 594;
UPDATE users SET cargo = 'Operador'          WHERE id = 576;
UPDATE users SET cargo = 'Operador'          WHERE id = 345;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 346;
UPDATE users SET cargo = 'Logística - OPE'   WHERE id = 593;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 671;
UPDATE users SET cargo = 'Logística - Mot'   WHERE id = 547;
UPDATE users SET cargo = 'Caldeiraria'       WHERE id = 347;
UPDATE users SET cargo = 'Operador'          WHERE id = 499;
UPDATE users SET cargo = 'Operador'          WHERE id = 500;  -- duplicate Marcelino Leandro
UPDATE users SET cargo = 'Operador'          WHERE id = 348;
UPDATE users SET cargo = 'Operador'          WHERE id = 541;
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 350;
UPDATE users SET cargo = 'Comercial'         WHERE id = 351;  -- Maria Fernanda Machado (truncated)
UPDATE users SET cargo = 'Comercial'         WHERE id = 352;
UPDATE users SET cargo = 'Comercial'         WHERE id = 555;  -- Maria Victoria Corcini (truncated)
UPDATE users SET cargo = 'DP'                WHERE id = 454;
UPDATE users SET cargo = 'DP'                WHERE id = 353;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 473;
UPDATE users SET cargo = 'Gestão Operacional' WHERE id = 354;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 620;  -- Mateus Junio (truncated)
UPDATE users SET cargo = 'Operador'          WHERE id = 355;
UPDATE users SET cargo = 'Mecânica'          WHERE id = 429;
UPDATE users SET cargo = 'MKT'               WHERE id = 357;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 358;
UPDATE users SET cargo = 'Operador'          WHERE id = 550;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 600;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 670;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 566;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 507;
UPDATE users SET cargo = 'Operador'          WHERE id = 362;
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 468;
UPDATE users SET cargo = 'Mecânica'          WHERE id = 651;
UPDATE users SET cargo = 'RH'                WHERE id = 432;
UPDATE users SET cargo = 'DP'                WHERE id = 535;
UPDATE users SET cargo = 'Manutenção'        WHERE id = 365;
UPDATE users SET cargo = 'Manutenção'        WHERE id = 366;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 433;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 367;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 623;
UPDATE users SET cargo = 'Soldas'            WHERE id = 368;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 528;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 665;
UPDATE users SET cargo = 'Operador'          WHERE id = 370;
UPDATE users SET cargo = 'Diretor'           WHERE id = 371;
UPDATE users SET cargo = 'Manutenção'        WHERE id = 527;
UPDATE users SET cargo = 'MKT'               WHERE id = 515;
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 637;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 669;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 661;
UPDATE users SET cargo = 'Geoteste'          WHERE id = 641;
UPDATE users SET cargo = 'Gestão'            WHERE id = 599;
UPDATE users SET cargo = 'Operador'          WHERE id = 376;
UPDATE users SET cargo = 'Soldas'            WHERE id = 377;
UPDATE users SET cargo = 'Gestão de obras'   WHERE id = 636;
UPDATE users SET cargo = 'Gestão Operacional' WHERE id = 435;
UPDATE users SET cargo = 'Caldeiraria'       WHERE id = 437;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 540;
UPDATE users SET cargo = 'Logística - Mot'   WHERE id = 551;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 479;
UPDATE users SET cargo = 'Ajudante'          WHERE id = 646;
UPDATE users SET cargo = 'Mecânica'          WHERE id = 387;
UPDATE users SET cargo = 'Logística - Mot'   WHERE id = 388;
UPDATE users SET cargo = 'Operador'          WHERE id = 397;
UPDATE users SET cargo = 'Operador'          WHERE id = 389;
UPDATE users SET cargo = 'Soldas'            WHERE id = 553;  -- Yosmar (CSV: Luces, DB: Lucas - minor diff)
