CREATE TABLE IF NOT EXISTS obra_producao (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  obra_id BIGINT UNSIGNED NOT NULL,
  diametro VARCHAR(60) NULL DEFAULT NULL,
  profundidade DECIMAL(10,2) NULL DEFAULT NULL,
  qtd_estacas INT NULL DEFAULT NULL,
  preco DECIMAL(12,2) NULL DEFAULT NULL,
  subtotal DECIMAL(14,2) NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY obra_producao_obra_id_index (obra_id),
  CONSTRAINT obra_producao_obra_id_foreign FOREIGN KEY (obra_id) REFERENCES constructions (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
